### ISSUE TITLE
Begin constructing V1 of website

### ISSUE THREAD

**Issue by JFrankfurt** [PhillipChaffee/MoonbaseFaucet#21]
@PhillipChaffee 
This is an example of what the games page might look like.
There should be a **directive** for the games. I expect you'll have a **service** call our api and ask it to return a game list. With the game list you would render out a screenshot or a quick clip of gameplay (whatever we decide to return to the call). Then, when the user's mouse enters a game, a blue screen should fade over the clip and display the game's name and a short description.
![games page](https://cloud.githubusercontent.com/assets/5773490/6475874/7d53efd2-c1dd-11e4-8a72-8245a77a8579.png)

**Comment by PhillipChaffee** [comment]
Verison 1 is just going to conatin the working ui router, game, and some styling.

**Comment by PhillipChaffee** [comment]
Finished with commit b3f6f5c17a44b08f2723effd539d125db420b544
